language: go

go:
  - 1.12.x

before_install:
  - env GO111MODULE=on go build

script:
  - env GO111MODULE=on go test -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
